version: '3.3'

services:
  db:
    container_name: movies_pg_db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movies_db
    ports:
      - 5432:5432
    volumes:
      - /db_movies/vol:/var/lib/postgresql/data
    networks:
      - movies-network
 
  api:
    container_name: movies
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./:/api
    networks:
      - movies-network  

networks:
  movies-network:  
